// Hotel API

GET {{url}}/hotels
Authorization: Bearer {{token}}

###

GET {{url}}/hotels/1
Authorization: Bearer {{token}}

###

POST {{url}}/hotels
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hotelName": "Radisson",
  "hotelAddress": "Sindelfingen",
  "hotelType": "BUDGET"
}

###

PUT {{url}}/hotels/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hotelName": "Scandic",
  "hotelAddress": "Lyngby Hovedgade",
  "hotelType": "BUDGET"
}

###

DELETE {{url}}/hotels/540
Authorization: Bearer {{token}}

###

// Room API

GET {{url}}/rooms/1
Authorization: Bearer {{token}}

###

// filter rooms by prize
GET {{url}}/rooms/hotel/1?min-price=2000&max-price=5000
Authorization: Bearer {{token}}

###

GET {{url}}/rooms/1
Authorization: Bearer {{token}}

###

POST {{url}}/rooms/hotel/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roomNumber": 112,
  "roomPrice": 1150,
  "roomType": "SINGLE"
}
